spring:
  h2:
    console:
      enabled: true
  profiles:
    active: @spring.profiles.active@
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
application:
  jwt:
    secret: tempsecret
  sendgrid:
    key:
    password-reset-template-id:
